# Generated by Django 3.0.7 on 2020-06-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='page',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
